{% set name = "cloudpathlib" %}
{% set version = "0.21.0" %}


package:
  name: cloudpathlib-meta
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb8f6b890a3d37b35f0eabff86721bb8d35dfc6a6be98c1f4d34b19e989c6641

build:
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
    - flit-core >=3.2,<4



outputs:
  - name: cloudpathlib
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv
    requirements:
      host:
        - pip
        - python >=3.8
        - flit-core >=3.2,<4
      run:
        - python >=3.8
        - typing_extensions
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
      requires:
        - pip

  - name: cloudpathlib-azure
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.8
        - flit-core >=3.2,<4
      run:
        - python >=3.8
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - azure-storage-blob >=12
        - azure-storage-file-datalake >=12
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['azure'].validate_completeness()"
      requires:
        - pip

  - name: cloudpathlib-gs
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.8
        - flit-core >=3.2,<4
      run:
        - python >=3.8
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - google-cloud-storage
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['gs'].validate_completeness()"
      requires:
        - pip

  - name: cloudpathlib-s3
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.8
        - flit-core >=3.2,<4
      run:
        - python >=3.8
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - boto3 >=1.34.0
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['s3'].validate_completeness()"
      requires:
        - pip

  - name: cloudpathlib-all
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.8
        - flit-core >=3.2,<4
      run:
        - python >=3.8
        - {{ pin_subpackage('cloudpathlib-azure', exact=True) }}
        - {{ pin_subpackage('cloudpathlib-gs', exact=True) }}
        - {{ pin_subpackage('cloudpathlib-s3', exact=True) }}
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['azure'].validate_completeness()"
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['gs'].validate_completeness()"
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['s3'].validate_completeness()"
      requires:
        - pip


about:
  home: https://github.com/drivendataorg/cloudpathlib
  summary: pathlib.Path-style classes for interacting with files in different cloud storage services.
  license: MIT
  license_file: LICENSE
  doc_url: https://cloudpathlib.drivendata.org/
  dev_url: https://github.com/drivendataorg/cloudpathlib

extra:
  feedstock-name: cloudpathlib
  recipe-maintainers:
    - jayqi
