{% set name = "cloudpathlib" %}
{% set version = "0.15.0" %}


package:
  name: cloudpathlib-meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0606158c97f0f249c03eae6ec2af142c911e6d455226b6c598f88e3a71f04390

build:
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7


outputs:
  - name: cloudpathlib
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv
    requirements:
      host: &host
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - importlib-metadata
        - typing_extensions
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
      requires:
        - pip

  - name: cloudpathlib-azure
    build:
      noarch: python
    requirements:
      host: *host
      run:
        - python >=3.7
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - azure-storage-blob >=12
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['azure'].validate_completeness()"
      requires:
        - pip

  - name: cloudpathlib-gs
    build:
      noarch: python
    requirements:
      host: *host
      run:
        - python >=3.7
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - google-cloud-storage
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['gs'].validate_completeness()"
      requires:
        - pip

  - name: cloudpathlib-s3
    build:
      noarch: python
    requirements:
      host: *host
      run:
        - python >=3.7
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - boto3
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['s3'].validate_completeness()"
      requires:
        - pip

  - name: cloudpathlib-all
    build:
      noarch: python
    requirements:
      host: *host
      run:
        - python >=3.7
        - {{ pin_subpackage('cloudpathlib-azure', exact=True) }}
        - {{ pin_subpackage('cloudpathlib-gs', exact=True) }}
        - {{ pin_subpackage('cloudpathlib-s3', exact=True) }}
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['azure'].validate_completeness()"
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['gs'].validate_completeness()"
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['s3'].validate_completeness()"
      requires:
        - pip


about:
  home: https://github.com/drivendataorg/cloudpathlib
  summary: pathlib.Path-style classes for interacting with files in different cloud storage services.
  license: MIT
  license_file: LICENSE
  doc_url: https://cloudpathlib.drivendata.org/
  dev_url: https://github.com/drivendataorg/cloudpathlib

extra:
  feedstock-name: cloudpathlib
  recipe-maintainers:
    - jayqi
