{% set name = "cloudpathlib" %}
{% set version = "0.2.0" %}


package:
  name: cloudpathlib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 086346877fb37f46434ae8c8b67ab55bf6b628ea9cb143cd0760952d958ebf42

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - importlib-metadata  # [py<38]

test:
  imports:
    - cloudpathlib
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: cloudpathlib

  - name: cloudpathlib-azure
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - azure-storage-blob >=12
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['azure'].validate_completeness()"
      requires:
        - pip

  - name: cloudpathlib-s3
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - boto3
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['s3'].validate_completeness()"
      requires:
        - pip

  - name: cloudpathlib-all
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - {{ pin_subpackage('cloudpathlib-azure', exact=True) }}
        - {{ pin_subpackage('cloudpathlib-s3', exact=True) }}
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['azure'].validate_completeness()"
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['s3'].validate_completeness()"
      requires:
        - pip


about:
  home: https://github.com/drivendataorg/cloudpathlib
  summary: pathlib.Path-style classes for interacting with files in different cloud storage services.
  license: MIT
  license_file: LICENSE
  doc_url: https://cloudpathlib.drivendata.org/
  dev_url: https://github.com/drivendataorg/cloudpathlib

extra:
  recipe-maintainers:
    - jayqi
