{% set name = "cloudpathlib" %}
{% set version = "0.10.0" %}


package:
  name: cloudpathlib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f18577832c95e47511bfc937caa2a014c1531f04e26359039095ed09f1e5ad4e

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - python
    - importlib-metadata  # [py<38]

test:
  imports:
    - cloudpathlib
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: cloudpathlib

  - name: cloudpathlib-azure
    requirements:
      host:
        - pip
        - python
      run:
        - python
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - azure-storage-blob >=12
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['azure'].validate_completeness()"
      requires:
        - pip

  - name: cloudpathlib-gs
    requirements:
      host:
        - pip
        - python
      run:
        - python
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - google-cloud-storage
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['gs'].validate_completeness()"
      requires:
        - pip

  - name: cloudpathlib-s3
    requirements:
      host:
        - pip
        - python
      run:
        - python
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - boto3
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['s3'].validate_completeness()"
      requires:
        - pip

  - name: cloudpathlib-all
    requirements:
      host:
        - pip
        - python
      run:
        - python
        - {{ pin_subpackage('cloudpathlib-azure', exact=True) }}
        - {{ pin_subpackage('cloudpathlib-gs', exact=True) }}
        - {{ pin_subpackage('cloudpathlib-s3', exact=True) }}
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['azure'].validate_completeness()"
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['gs'].validate_completeness()"
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['s3'].validate_completeness()"
      requires:
        - pip


about:
  home: https://github.com/drivendataorg/cloudpathlib
  summary: pathlib.Path-style classes for interacting with files in different cloud storage services.
  license: MIT
  license_file: LICENSE
  doc_url: https://cloudpathlib.drivendata.org/
  dev_url: https://github.com/drivendataorg/cloudpathlib

extra:
  recipe-maintainers:
    - jayqi
