{% set name = "cloudpathlib" %}
{% set version = "0.13.0" %}


package:
  name: cloudpathlib-meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7135f975b28917348f3ca8feb85f83277c89ac9acf331d1b87d945ecdbe2dffb

build:
  number: 1
  noarch: python

outputs:
  - name: cloudpathlib
    build:
      number: 1
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - importlib-metadata
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
      requires:
        - pip

  - name: cloudpathlib-azure
    build:
      number: 1
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - azure-storage-blob >=12
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['azure'].validate_completeness()"
      requires:
        - pip

  - name: cloudpathlib-gs
    build:
      number: 1
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - google-cloud-storage
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['gs'].validate_completeness()"
      requires:
        - pip

  - name: cloudpathlib-s3
    build:
      number: 1
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - boto3
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['s3'].validate_completeness()"
      requires:
        - pip

  - name: cloudpathlib-all
    build:
      number: 1
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage('cloudpathlib-azure', exact=True) }}
        - {{ pin_subpackage('cloudpathlib-gs', exact=True) }}
        - {{ pin_subpackage('cloudpathlib-s3', exact=True) }}
    test:
      imports:
        - cloudpathlib
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['azure'].validate_completeness()"
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['gs'].validate_completeness()"
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['s3'].validate_completeness()"
      requires:
        - pip


about:
  home: https://github.com/drivendataorg/cloudpathlib
  summary: pathlib.Path-style classes for interacting with files in different cloud storage services.
  license: MIT
  license_file: LICENSE
  doc_url: https://cloudpathlib.drivendata.org/
  dev_url: https://github.com/drivendataorg/cloudpathlib

extra:
  feedstock-name: cloudpathlib
  recipe-maintainers:
    - jayqi
